[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cpi_swap_program = "BkY6rmiB7f2X5buFpvaTBQJhbPdiJybDVmsXLcFq6m7L"
mock_jupiter = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
spree_points = "4tMWWjzrvgqdTPrRynnSmzwVDS2RyfCxXhEzSjJH1A1p"
token_deployer = "3qGYKoUN2dxCqxbGYLPBFSZaXNLLt1rVwsJTfbah9gE6"
transfer_hook = "9YGF4qqsGHg7h7FbxuPq8odvicBcAEJumSxFsCbXyAmt"



[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
