[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cpi_swap_program = "BkY6rmiB7f2X5buFpvaTBQJhbPdiJybDVmsXLcFq6m7L"
mock_jupiter = "JA1v2pi2o7yG79hHFqADtSgPZHmMspnKHGcecPAeK9pa"
spree_points = "4tMWWjzrvgqdTPrRynnSmzwVDS2RyfCxXhEzSjJH1A1p"
token_deployer = "CEzsTf7eM9ac1kGx7DuZHdXv8b4mLPQBbRzrQcMJmJBh"
transfer_hook = "6DkyQp5UoCkxubGGGBFhDsMP4yiuAg2PciJBQKJHD35E"



[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
